# GraphicalLassoCV Example

Last Update: July 22nd, 2020

Reference: https://scikit-learn.org/stable/modules/generated/sklearn.covariance.GraphicalLasso.html

In [17]:
# Import all the necessary packages
import numpy as np
import pandas as pd
from sklearn.covariance import GraphicalLassoCV
from sklearn.covariance import GraphicalLasso
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
# Define true covariance matrix
true_cov = np.array([[0.8, 0.0, 0.2, 0.0],
                     [0.0, 0.4, 0.0, 0.0],
                     [0.2, 0.0, 0.3, 0.1],
                     [0.0, 0.0, 0.1, 0.7]])

# Set seed and generate X from multivaraite norm with specified covariance
np.random.seed(0)
X = np.random.multivariate_normal(mean=[0, 0, 0, 0], cov=true_cov, size=200)
X.shape

(200, 4)

In [3]:
# True precision matrix calculated from the inverse of true covariance matrix
true_prec = np.linalg.inv(true_cov)
true_prec

array([[ 1.51515152,  0.        , -1.06060606,  0.15151515],
       [ 0.        ,  2.5       ,  0.        ,  0.        ],
       [-1.06060606,  0.        ,  4.24242424, -0.60606061],
       [ 0.15151515,  0.        , -0.60606061,  1.51515152]])

In [4]:
# Fit the GraphicalLassoCV model
est = GraphicalLassoCV(max_iter = 1000).fit(X)

In [5]:
# The estimated covariance matrix from GraphicalLassoCV
np.around(est.covariance_, decimals=3)

array([[0.816, 0.051, 0.22 , 0.017],
       [0.051, 0.364, 0.018, 0.036],
       [0.22 , 0.018, 0.322, 0.094],
       [0.017, 0.036, 0.094, 0.69 ]])

In [6]:
# The estimated precision matrix from GraphicalLassoCV
np.around(est.precision_, decimals=3)

array([[ 1.521, -0.17 , -1.063,  0.116],
       [-0.17 ,  2.784, -0.   , -0.14 ],
       [-1.063, -0.   ,  3.982, -0.518],
       [ 0.116, -0.14 , -0.518,  1.524]])

In [7]:
# The list of lambdas used in cross validation
est.cv_results_["alphas"]

array([0.22813021, 0.04914916, 0.02659803, 0.01439404, 0.01058887,
       0.00880744, 0.00848886, 0.00818181, 0.00788587, 0.00778962,
       0.00760063, 0.00732571, 0.00609326, 0.00506815, 0.0042155 ,
       0.0022813 , 0.        ])

In [8]:
# The lambda chosen by cross validation
est.alpha_

0.008181811323310086

In [9]:
# The index of the chosen lambda in the list of lambdas
ind_lambda = np.where(est.cv_results_["alphas"] == est.alpha_)[0][0]
ind_lambda

7

In [36]:
grid_scores = np.round(np.hstack((est.cv_results_["split0_test_score"].reshape(-1, 1), \
                       est.cv_results_["split1_test_score"].reshape(-1, 1), \
                        est.cv_results_["split2_test_score"].reshape(-1, 1), \
                        est.cv_results_["split3_test_score"].reshape(-1, 1), \
                        est.cv_results_["split4_test_score"].reshape(-1, 1))
                        ), 3)
grid_scores

array([[-4.505, -4.166, -4.24 , -4.235, -4.238],
       [-4.314, -4.045, -4.167, -4.174, -4.165],
       [-4.281, -4.037, -4.161, -4.175, -4.171],
       [-4.263, -4.033, -4.162, -4.174, -4.178],
       [-4.257, -4.03 , -4.163, -4.175, -4.181],
       [-4.254, -4.028, -4.163, -4.176, -4.183],
       [-4.254, -4.028, -4.164, -4.176, -4.183],
       [-4.253, -4.028, -4.164, -4.176, -4.183],
       [-4.253, -4.027, -4.164, -4.176, -4.184],
       [-4.252, -4.027, -4.164, -4.176, -4.184],
       [-4.252, -4.027, -4.165, -4.176, -4.184],
       [-4.252, -4.027, -4.165, -4.176, -4.184],
       [-4.25 , -4.026, -4.167, -4.178, -4.186],
       [-4.248, -4.025, -4.169, -4.18 , -4.187],
       [-4.247, -4.025, -4.171, -4.181, -4.188],
       [-4.244, -4.023, -4.174, -4.184, -4.19 ],
       [-4.395, -4.038, -4.195, -4.209, -4.416]])

In [10]:
#grid_scores_ndarray of shape (n_alphas, n_folds): Log-likelihood score on left-out data across folds.
np.round(est.grid_scores_, 3)

array([[-4.505, -4.166, -4.24 , -4.235, -4.238],
       [-4.314, -4.045, -4.167, -4.174, -4.165],
       [-4.281, -4.037, -4.161, -4.175, -4.171],
       [-4.263, -4.033, -4.162, -4.174, -4.178],
       [-4.257, -4.03 , -4.163, -4.175, -4.181],
       [-4.254, -4.028, -4.163, -4.176, -4.183],
       [-4.254, -4.028, -4.164, -4.176, -4.183],
       [-4.253, -4.028, -4.164, -4.176, -4.183],
       [-4.253, -4.027, -4.164, -4.176, -4.184],
       [-4.252, -4.027, -4.164, -4.176, -4.184],
       [-4.252, -4.027, -4.165, -4.176, -4.184],
       [-4.252, -4.027, -4.165, -4.176, -4.184],
       [-4.25 , -4.026, -4.167, -4.178, -4.186],
       [-4.248, -4.025, -4.169, -4.18 , -4.187],
       [-4.247, -4.025, -4.171, -4.181, -4.188],
       [-4.244, -4.023, -4.174, -4.184, -4.19 ],
       [-4.395, -4.038, -4.195, -4.209, -4.416]])

In [39]:
# Summary information 
alphas = np.array(est.cv_results_["alphas"]).reshape(len(est.cv_results_["alphas"]),1)
df_temp = pd.DataFrame(np.concatenate((alphas,grid_scores),axis = 1),
                       columns = ['lambdas','score_fold1','score_fold2','score_fold3','score_fold4','score_fold5'])
df_temp['Total_score'] = grid_scores.sum(axis = 1)
df_temp['Average_score'] = grid_scores.sum(axis = 1)/grid_scores.shape[1]
df_temp

lambdas  score_fold1  score_fold2  score_fold3  score_fold4  score_fold5  \
0   0.228130       -4.505       -4.166       -4.240       -4.235       -4.238   
1   0.049149       -4.314       -4.045       -4.167       -4.174       -4.165   
2   0.026598       -4.281       -4.037       -4.161       -4.175       -4.171   
3   0.014394       -4.263       -4.033       -4.162       -4.174       -4.178   
4   0.010589       -4.257       -4.030       -4.163       -4.175       -4.181   
5   0.008807       -4.254       -4.028       -4.163       -4.176       -4.183   
6   0.008489       -4.254       -4.028       -4.164       -4.176       -4.183   
7   0.008182       -4.253       -4.028       -4.164       -4.176       -4.183   
8   0.007886       -4.253       -4.027       -4.164       -4.176       -4.184   
9   0.007790       -4.252       -4.027       -4.164       -4.176       -4.184   
10  0.007601       -4.252       -4.027       -4.165       -4.176       -4.184   
11  0.007326       -4.252       -4.027       -4.165       -4.176       -4.184   
12  0.006093       -4.250       -4.026       -4.167       -4.178       -4.186   
13  0.005068       -4.248       -4.025       -4.169       -4.180       -4.187   
14  0.004216       -4.247       -4.025       -4.171       -4.181       -4.188   
15  0.002281       -4.244       -4.023       -4.174       -4.184       -4.190   
16  0.000000       -4.395       -4.038       -4.195       -4.209       -4.416   

    Total_score  Average_score  
0       -21.384        -4.2768  
1       -20.865        -4.1730  
2       -20.825        -4.1650  
3       -20.810        -4.1620  
4       -20.806        -4.1612  
5       -20.804        -4.1608  
6       -20.805        -4.1610  
7       -20.804        -4.1608  
8       -20.804        -4.1608  
9       -20.803        -4.1606  
10      -20.804        -4.1608  
11      -20.804        -4.1608  
12      -20.807        -4.1614  
13      -20.809        -4.1618  
14      -20.812        -4.1624  
15      -20.815        -4.1630  
16      -21.253        -4.2506

In [41]:
# Find the precision matrix and number of zero entries in the matrix for each lambda
prec_mx_list = []
num_zeros_list = []

for i in range(len(est.cv_results_["alphas"])):
    est_lambda = GraphicalLasso(alpha = est.cv_results_["alphas"][i], max_iter = 1000).fit(X)
    prec_mx_list.append(est_lambda.precision_)
    
    non_zero = (np.abs(est_lambda.precision_) > 0.02)
    num_zeros = non_zero.shape[0] * non_zero.shape[1] - np.sum(non_zero*1)
    num_zeros_list.append(num_zeros)
    
    print('For lambda = ', est.cv_results_["alphas"][i])
    print('Number of zero entries in the precision matrix is : ', num_zeros)

For lambda =  0.22813020648178528
Number of zero entries in the precision matrix is :  12
For lambda =  0.049149163068849484
Number of zero entries in the precision matrix is :  6
For lambda =  0.026598029308124216
Number of zero entries in the precision matrix is :  2
For lambda =  0.014394042927746542
Number of zero entries in the precision matrix is :  2
For lambda =  0.010588866190156324
Number of zero entries in the precision matrix is :  2
For lambda =  0.008807435274025993
Number of zero entries in the precision matrix is :  2
For lambda =  0.008488861740795791
Number of zero entries in the precision matrix is :  2
For lambda =  0.008181811323310086
Number of zero entries in the precision matrix is :  2
For lambda =  0.007885867219221507
Number of zero entries in the precision matrix is :  2
For lambda =  0.007789617396298071
Number of zero entries in the precision matrix is :  2
For lambda =  0.00760062770233054
Number of zero entries in the precision matrix is :  2
For lambda 

In [42]:
# Add the number of zeros information to the summary information dataframe
df_temp['Num_Zeros'] = np.array(num_zeros_list)
df_temp

lambdas  score_fold1  score_fold2  score_fold3  score_fold4  score_fold5  \
0   0.228130       -4.505       -4.166       -4.240       -4.235       -4.238   
1   0.049149       -4.314       -4.045       -4.167       -4.174       -4.165   
2   0.026598       -4.281       -4.037       -4.161       -4.175       -4.171   
3   0.014394       -4.263       -4.033       -4.162       -4.174       -4.178   
4   0.010589       -4.257       -4.030       -4.163       -4.175       -4.181   
5   0.008807       -4.254       -4.028       -4.163       -4.176       -4.183   
6   0.008489       -4.254       -4.028       -4.164       -4.176       -4.183   
7   0.008182       -4.253       -4.028       -4.164       -4.176       -4.183   
8   0.007886       -4.253       -4.027       -4.164       -4.176       -4.184   
9   0.007790       -4.252       -4.027       -4.164       -4.176       -4.184   
10  0.007601       -4.252       -4.027       -4.165       -4.176       -4.184   
11  0.007326       -4.252       -4.027       -4.165       -4.176       -4.184   
12  0.006093       -4.250       -4.026       -4.167       -4.178       -4.186   
13  0.005068       -4.248       -4.025       -4.169       -4.180       -4.187   
14  0.004216       -4.247       -4.025       -4.171       -4.181       -4.188   
15  0.002281       -4.244       -4.023       -4.174       -4.184       -4.190   
16  0.000000       -4.395       -4.038       -4.195       -4.209       -4.416   

    Total_score  Average_score  Num_Zeros  
0       -21.384        -4.2768         12  
1       -20.865        -4.1730          6  
2       -20.825        -4.1650          2  
3       -20.810        -4.1620          2  
4       -20.806        -4.1612          2  
5       -20.804        -4.1608          2  
6       -20.805        -4.1610          2  
7       -20.804        -4.1608          2  
8       -20.804        -4.1608          2  
9       -20.803        -4.1606          2  
10      -20.804        -4.1608          2  
11      -20.804        -4.1608          2  
12      -20.807        -4.1614          2  
13      -20.809        -4.1618          2  
14      -20.812        -4.1624          2  
15      -20.815        -4.1630          2  
16      -21.253        -4.2506          0

In [43]:
# Estimated precision matrix for the first lambda
prec_mx_list[0]

array([[ 1.22596272, -0.        , -0.        , -0.        ],
       [-0.        ,  2.74605582, -0.        , -0.        ],
       [-0.        , -0.        ,  3.10477899, -0.        ],
       [-0.        , -0.        , -0.        ,  1.44860969]])

In [44]:
# Estimated precision matrix for the second lambda
prec_mx_list[1]

array([[ 1.39660482, -0.03306993, -0.7758674 ,  0.        ],
       [-0.03306993,  2.74694758, -0.        , -0.        ],
       [-0.7758674 , -0.        ,  3.57628844, -0.24337161],
       [ 0.        , -0.        , -0.24337161,  1.46744183]])

In [45]:
# Estimated precision matrix for the chosen lambda
prec_mx_list[ind_lambda]

array([[ 1.52069737, -0.17033761, -1.06283639,  0.11603294],
       [-0.17033761,  2.78366128, -0.        , -0.14048774],
       [-1.06283639, -0.        ,  3.98232618, -0.51782878],
       [ 0.11603294, -0.14048774, -0.51782878,  1.52380577]])